/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.Services.UserBookingServices;
import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.util.UserServiceUtil;

import java.io.IOException;
import java.util.*;

public class App {

    public static void main(String[] args) {
        System.out.println("Runnign Train Booking System");
        Scanner scanner = new Scanner(System.in);
        int option = 0;
        UserBookingServices userBookingServices;
        try {
            userBookingServices = new UserBookingServices();
        }catch (IOException ex){
            System.out.println("These is somthing wrong");
            return;
        }
        while (option != 7){
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");
            option = scanner.nextInt();
            Train trainSelectedforBooking = new Train();
            switch (option){
                case 1:
                    System.out.println("Enter the username to signup");
                    String nameToSignUp = scanner.next();
                    System.out.println("Enter the password to signup");
                    String passwordToSignUp = scanner.next();
                    User usreToSignup = new User(nameToSignUp, passwordToSignUp, UserServiceUtil.hashPassword(passwordToSignUp),new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingServices.signUp(usreToSignup);
                    break;
                case 2:
                    System.out.println("Enter the username to Login");
                    String nameToLogin = scanner.next();
                    System.out.println("Enter the password to signup");
                    String passwordToLogin = scanner.next();
                    User userToLgin = new User(nameToLogin, passwordToLogin, UserServiceUtil.hashPassword(passwordToLogin), new ArrayList<>(), UUID.randomUUID().toString());
                    try {
                        userBookingServices = new UserBookingServices(userToLgin);
                    }catch (IOException ex){
                        return;
                    }
                    break;
                case 3:
                    System.out.println("Fetch your booking");
                    userBookingServices.fetchBooking();
                    break;
                case 4:
                    System.out.println("Type your source station");
                    String source = scanner.next();
                    System.out.println("Type your destination station");
                    String dest = scanner.next();
                    List<Train> trains = userBookingServices.getTrains(source, dest);
                    int index = 1;
                    for (Train t : trains){
                        System.out.println(index+"Train id : "+t.getTrainId());
                        for (Map.Entry<String, String> entry: t.getStationTimes().entrySet()){
                            System.out.println("station"+entry.getKey()+"time"+entry.getValue());
                        }
                    }
                    System.out.println("Select a train by typing 1,2,3....");
                    trainSelectedforBooking =trains.get(scanner.nextInt());
                    break;
                case 5:
                    System.out.println("Select a seat out of these seats");
                    List<List<Integer>> seats = userBookingServices.featchSeat(trainSelectedforBooking);
                    for (List<Integer> row : seats){
                        for (Integer val : row){
                            System.out.print(val+" ");
                        }
                        System.out.println();
                    }
                    System.out.println("Select the seat by typing the row and column");
                    System.out.println("Enter the row");
                    int row = scanner.nextInt();
                    System.out.println("Enter your column");
                    int col = scanner.nextInt();
                    System.out.println("Booking your seat....");
                    Boolean booked = userBookingServices.bookTrainsSeaats(trainSelectedforBooking,row,col);
                    if (booked.equals(Boolean.TRUE)){
                        System.out.println("Booked! enjoy your journey");
                    }else {
                        System.out.println("Cat'r book this seat");
                    }
                    break;
                default:
                    break;
            }
        }
    }
}
